[package]
name = "simul-three-cushion"
version = "0.0.0"
edition = "2021"
rust-version = "1.91"
publish = false

[lints]
workspace = true

[dependencies]
billiards = { path = "../.." }
clap = { version = "4.5", features = ["derive"] }

[dev-dependencies]
criterion = "0.5"
simul = { path = "../../../simul" }

[[bench]]
name = "direct_trials"
harness = false
